name: args
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
 Libraries for defining parsers for parsing raw command-line arguments into
 a set of options and values using GNU and POSIX style options.


dependencies:
  unittest:
    sdk: unittest
