name: serialization
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  Provide a serialization facility for Dart objects.
dependencies:
  unittest:
    sdk: unittest
