name: solar3d
description: 3D Solar System Demo
version: 0.0.1
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/solar3d
dependencies:
  browser: any
  vector_math: any
